### ISSUE TITLE
Code is broken

### ISSUE THREAD

**Issue by RDIL** [dowlandaiello/corona-inc#1]
:b:roke :(

throws Google Maps JavaScript API error: InvalidKeyMapError
https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error

**Comment by dowlandaiello** [comment]
Code is not ":b: roken." At the moment, you need an API key for google maps from GCP.

**Comment by RDIL** [comment]
Aha.  Might want to mention it in the readme since that was the instructions I was following

**Comment by dowlandaiello** [comment]
@RDIL Updated the readme.
