### ISSUE TITLE
Can't open website

### ISSUE THREAD

**Issue by Destaq** [dowlandaiello/corona-inc#2]
Going to itzcoronatime.com throws a 'the server took to long to respond' error, and thus I am unable to interact with the content.

**Comment by lexzaiello** [comment]
My apologies—I’ve abandoned this project, as John’s Hopkins hasn’t committed to a stable schema for their COVID-19 data dumps, and refactoring the parser every few weeks just isn’t practical. I might consider migrating over to worldometer’s API, but there just isn’t much demand for this project at the moment.

**Comment by Destaq** [comment]
OK, thank you for the reply. Do let me know if you ever reopen the project again, it looked cool : )
